### ISSUE TITLE
Remote network device unreachable after upgrade from 2019.10.0 to 2020.3.0

### ISSUE THREAD

**Issue by dpizzle** [mirceaulinic/salt-sproxy#135]
**Describe the bug**
After upgrading from `2019.10.0` to `2020.3.0`, I am unable to reach Juniper devices using the napalm module. The devices are listed in the salt pillar file as before.

**Steps To Reproduce**

```
$ cat /etc/salt/master

pillar_roots:
  base:
    - /etc/salt/pillar

$ cat /etc/salt/pillar/top.sls

base: 
  test_switch:
    - napalm_junos

$ cat /etc/salt/pillar/napalm_junos.sls

proxy:
  proxytype: napalm
  driver: junos
  host: {{ grains['id'] }}
  username: testuser
  passwd: testpass
```

```
$ salt-sproxy 'test_switch' test.ping
test_switch:
    Minion did not return. [No response]
ERROR: Minions returned with non-zero exit code
```

Replacing `{{ grains['id'] }}` with `test_switch` in the `napalm_junos.sls` file didn't resolve the issue.

**Versions Report**

```
salt-sproxy 2020.3.0
/etc/salt # salt-sproxy -V
Salt Version:
           Salt: 3000.3
    Salt SProxy: 2020.3.0

Dependency Versions:
        Ansible: Not Installed
           cffi: 1.14.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
     junos-eznc: 2.2.1
       jxmlease: 1.0.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
         NAPALM: 2.5.0
       ncclient: 0.6.7
        Netmiko: 2.4.2
       paramiko: 2.7.1
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pyeapi: 0.8.3
         pygit2: Not Installed
       PyNetBox: Not Installed
          PyNSO: Not Installed
         Python: 3.6.9 (default, Oct 17 2019, 11:10:22)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 19.0.1
            scp: 0.13.2
          smmap: Not Installed
        textfsm: 1.1.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: Not Installed
```
