### ISSUE TITLE
Question: using salt-sproxy as a replacement for salt-ssh

### ISSUE THREAD

**Issue by dmacvicar** [mirceaulinic/salt-sproxy#179]
I have tried to replace my salt-ssh usage with salt-sproxy. This means a plain git repo, with a `Saltfile` like [described here](https://duncan.codes/posts/2016-05-18-using-salt-like-ansible/index.html). I had mixed success.

Changing my Saltfile from:

```yaml
salt-ssh:
  config_dir: etc/salt
  max_procs: 30
  wipe_ssh: True
```
to
```yaml
salt-sproxy:
  config_dir: etc/salt
  max_procs: 30
  wipe_ssh: True
```

Added some paramers to `etc/salt/master`
```diff
diff --git a/etc/salt/master b/etc/salt/master
index 3395db0..b81a197 100644
--- a/etc/salt/master
+++ b/etc/salt/master
@@ -1,3 +1,7 @@
+roster: file
+sync_proxy: true
+sync_executors: true
+
```

For some reason ssh keys and user did not work, so I added root/password to `etc/salt/roster`

After applying a pillar `ssh.sls` to all machines with the content:

```yaml
proxy:
  proxytype: ssh
```

I got it "working". But I could only call `test.ping`. Anything with arguments did not return anything. After reading `salt-ssh` code I noticed the client was constructed differently and the args/kwargs where passed in the client. Changing it to:

```diff
diff --git a/salt_sproxy/_proxy/ssh.py b/salt_sproxy/_proxy/ssh.py
index f729b21..9a44c2f 100644
--- a/salt_sproxy/_proxy/ssh.py
+++ b/salt_sproxy/_proxy/ssh.py
@@ -105,8 +105,18 @@ def _prep_conn(opts, fun, *args, **kwargs):
     fsclient = salt.fileclient.FSClient(opts)
     # TODO: Have here more options to simplify the usage, through features like
     # auto-expand the path to the priv key, auto-discovery, etc.
+    argv = [fun]
+    argv.extend([salt.utils.json.dumps(arg) for arg in args])
+    argv.extend(
+        [
+            "{0}={1}".format(
+                salt.utils.stringutils.to_str(key), salt.utils.json.dumps(val)
+            )
+            for key, val in six.iteritems(kwargs)
+        ]
+    )
     conn = salt.client.ssh.Single(
-        opts, [fun], opts['id'], fsclient=fsclient, **opts['proxy']
+        opts, argv, opts['id'], fsclient=fsclient, **opts['proxy']
     )
     conn.args = args
     conn.kwargs = kwargs
```

allowed me to call more functions. I did not succeed with `state.apply` but at least `cmd.run` is working with and without the patch. `grain.items` works but I swear it broke in some of the combinations I tested.

Without the patch I get:

```
[ERROR   ] [rpi02] Passed invalid arguments: run() missing 1 required positional argument: 'cmd'.  
```

and the module documentation as output.

Note: I haven't tested running this from a proper master.

**Comment by mirceaulinic** [comment]
Hi @dmacvicar. I've never used the Saltfile before, so first things first - let's clarify the `state.apply` issue, which I'm not able to reproduce. I have the following setup:

```bash
$ tree /srv/salt
/srv/salt/
|-- pillar/
|   |-- ssh.sls
|   `-- top.sls
|-- states/
    |-- files.sls
    |-- pkgs.sls
    |-- templates/
    |   `-- etc/
    |       `-- salt/
    |           `-- minion.jinja
    `-- top.sls
```

``/srv/salt/pillar/top.sls``

```yaml
base:
  '*':
    - ssh
```

``/srv/salt/pillar/ssh.sls``

```yaml
proxy:
  proxytype: ssh
  user: root
  priv: /home/mircea/.ssh/id_ed25519
```

``/etc/salt/master``

```yaml
pillar_roots:
  base:
  - /srv/salt/pillar

file_roots:
  base:
    - /srv/salt/states

sync_proxy: true
sync_executors: true

roster: file
roster_file: /etc/salt/roster
```

``/etc/salt/roster``

```yaml
srv:
  host: <IP address>
```

``/srv/salt/states/top.sls``

```yaml
base:
  '*':
    - pkgs
    - files
```

``/srv/salt/states/pkgs.sls``

```yaml
vim:
  pkg.installed

ack:
  pkg.installed
```

``/srv/salt/states/pkgs.sls``

```yaml
/etc/salt/minion:
  file.managed:
    - source: salt://templates/etc/salt/minion.jinja
    - makedirs: true
```

With that, I can run without any issues:

```
$ salt-sproxy srv state.apply
srv:
----------
          ID: vim
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 13:41:58.981253
    Duration: 39.485 ms
     Changes:   
----------
          ID: ack
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 13:41:59.020987
    Duration: 24.168 ms
     Changes:   
----------
          ID: /etc/salt/minion
    Function: file.managed
      Result: True
     Comment: File /etc/salt/minion is in the correct state
     Started: 13:41:59.048389
    Duration: 25.753 ms
     Changes:   

Summary for srv
------------
Succeeded: 3
Failed:    0
------------
Total states run:     3
Total run time:  89.406 ms
```

Can you confirm you're seeing the same with this setup? Also, what does `salt-sproxy -V` shows?
