### ISSUE TITLE
Question: Matching with grains in Ansible and Pillar rosters 

### ISSUE THREAD

**Issue by kzorba** [mirceaulinic/salt-sproxy#55]
Hi Mircea,

using the ansible roster I managed to have host groupings and be able to use them in salt-sproxy target selections (eg salt-sproxy -N FOO --preview-targets works as expected).

However using static grains I didn't manage to perform a match using -G '<grain>:<value>' with both ansible and pillar rosters. Is this still not implemented?

Thanks,
Kostas

PS: I had a look at the code (eg _roster/ansible.py) but can't figure out what happens in case of tgt_type in ['grain', 'grain_pcre']...

**Comment by mirceaulinic** [comment]
Hi @kzorba. That's a good question. The Ansible Roster currently doesn't do anything on the Grains, so it doesn't match anything due to their nature (which depends on many things, and can become very complicated). However, it might be doable to have matching on the static Grains. I'll mark this as a feature request and I'll try to implement it soon. Cheers!

**Comment by kzorba** [comment]
Yes, matching on static Grains would give good extra functionality for target selection. If you can do that for pillar roster (or netbox, haven't checked into that) that would be great!
Also, is there a way to perform nodegroup arrangement/selection using the pillar roster? You can do that with ansible roster and the hierarchical example you describe in your documentation.

**Comment by mirceaulinic** [comment]
FYI: Not directly related to the core issue here, but maybe #60 helps with some clarification on managing static Grains.

**Comment by kzorba** [comment]
So, defining static grains like mentioned in #60 would make matching with grains possible in salt-sproxy (using -G)?

**Comment by mirceaulinic** [comment]
#60 would help in this direction, but it is not sufficient on itself (i.e., it only builds the Grains); I have another branch I'm working for the counter-part that'd allow `-G` targeting. Hope to have this done by the end of the week. :smile:

**Comment by mirceaulinic** [comment]
Hey @kzorba - can you give #61 a try. Check out the document in the PR https://github.com/mirceaulinic/salt-sproxy/blob/c363aaf06ba47baf100da66571540144f1d700a6/docs/targeting.rst as well as https://salt-sproxy.readthedocs.io/en/develop/grains.html and https://salt-sproxy.readthedocs.io/en/develop/roster.html#configuring-static-grains for more details. Feel free to ask if you have any questions.

**Comment by mirceaulinic** [comment]
I went ahead a merged #61. If you wanna take a look, check this document out https://salt-sproxy.readthedocs.io/en/develop/targeting.html (and perhaps these two new options too: [--invasive-targeting](https://salt-sproxy.readthedocs.io/en/develop/opts.html#cmdoption-invasive-targeting) and [--preload-targeting](https://salt-sproxy.readthedocs.io/en/develop/opts.html#cmdoption-preload-targeting)).
If you're using the [salt-sproxy Docker image](https://hub.docker.com/r/mirceaulinic/salt-sproxy), you can use [this](https://hub.docker.com/layers/mirceaulinic/salt-sproxy/dev/images/sha256-4f79b3f683b5d6396674bca15ffd2d5b45fa5cfd101a71e3bfe66ad56f125ca6) tag if that's easier for you.

**Comment by kzorba** [comment]
Hi @mirceaulinic, I built my own docker image using your develop branch and I get the following exception (salt version 2019.2.2):

```
root@salt-sproxy2:/# salt-sproxy --version
salt-sproxy 2019.10.0
root@salt-sproxy2:/# salt-sproxy '*' test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'Values' object has no attribute 'sync'
Traceback (most recent call last):
  File "/usr/local/bin/salt-sproxy", line 11, in <module>
    load_entry_point('salt-sproxy==2019.10.0', 'console_scripts', 'salt-sproxy')()
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/scripts.py", line 18, in salt_sproxy
    client.run()
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/cli.py", line 231, in run
    if getattr(self.options, kwargs_opt) is not None:
AttributeError: 'Values' object has no attribute 'sync'
Traceback (most recent call last):
  File "/usr/local/bin/salt-sproxy", line 11, in <module>
    load_entry_point('salt-sproxy==2019.10.0', 'console_scripts', 'salt-sproxy')()
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/scripts.py", line 18, in salt_sproxy
    client.run()
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/cli.py", line 231, in run
    if getattr(self.options, kwargs_opt) is not None:
AttributeError: 'Values' object has no attribute 'sync'
```

Hopefully I am not doing anything stupid...

**Comment by mirceaulinic** [comment]
Oops, my bad - I've renamed the `--sync` option to `--static`, and left something behind, now fixed via #67. Can you re-build your container using the develop branch and try again? Cheers!

**Comment by mirceaulinic** [comment]
I believe this should be fixed by now, will release version 2020.2.0 in a few days. Of course, please feel free to reopen otherwise and we'll look into it.

**Comment by kzorba** [comment]
Hello @mirceaulinic , really sorry for my disappearance I had in my to-do list to provide input for this but was overwhelmed with other tasks.
I built a docker container in my environment with latest versions:

```
root@salt-sproxy2:/# pip3 list --format=legacy | egrep 'salt|ansible|napalm'
ansible (2.9.5)
napalm (2.5.0)
napalm-yang (0.1.0)
salt (3000)
salt-sproxy (2020.2.0)
```
I tested pillar and ansible rosters with various combinations. I confirm things are working **except** `Grain PCRE` `-P` queries on static grains.

To reproduce, here is my test ansible inventory file:

```
all:
  children:
    virtual:
      hosts:
        edge1-us:
          grains:
            role: pe1
            site: [ us, miami ]
        edge1-fr:
          grains:
            role: [ transit, peering ]
            site: [ fr, paris ]
        edge1-mf:
          grains:
            role: pe
            site: mf
        edge1-gp:
          grains:
            role: pe
            site: [ gp, baif ]
        edge1-mq:
          grains:
            role: pe
            site: mq
        edge1-gf:
          grains:
            role: pe
            site: gf
    physical:
      hosts:
        mx240-lab:
          grains:
            role: physical
        mx104-lab:
          grains:
            role: physical
        mx51-lab:
          grains:
            role: physical
        mx52-lab:
          grains:
            role: physical
```
And the failure:

```
root@salt-sproxy2:/# salt-sproxy -P "role:pe1" --preview-target
Exception occurred in runner proxy.execute: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt/client/mixins.py", line 374, in low
    data['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/_runners/proxy.py", line 1224, in execute
    rtargets_roster = roster_modules[roster](_tgt, tgt_type=_tgt_type)
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/ansible.py", line 153, in targets
    return engine(pool, tgt, opts=__opts__)
  File "/usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__init__.py", line 114, in grain_pcre
    log.debug('Grain PCRE matching on %s, over %s', tgt, tgtpool)
NameError: name 'tgtpool' is not defined
```

The fix seems to be trivial, typo most probably:

```
root@salt-sproxy2:/# diff -uN /usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__init__.py.orig /usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__init__.py
--- /usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__init__.py.orig 2020-02-19 16:11:07.864369140 +0000
+++ /usr/local/lib/python3.6/dist-packages/salt_sproxy/_roster/__init__.py      2020-02-19 16:11:29.220784086 +0000
@@ -111,7 +111,7 @@
     '''
     '''
     delimiter = opts.get('delimiter', DEFAULT_TARGET_DELIM)
-    log.debug('Grain PCRE matching on %s, over %s', tgt, tgtpool)
+    log.debug('Grain PCRE matching on %s, over %s', tgt, pool)
     ret = {
         minion: pool[minion]
         for minion in pool.keys()

```

By the way, compound matching is really cool.
Thanks for all your work!

Kostas
